name: codematic-youtube-backend CI/CD

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Debug npm and Node versions
        run: |
          npm --version
          node --version
      - name: List package.json content
        run: cat package.json
      - name: Check if package-lock.json exists
        run: |
          if [ -f package-lock.json ]; then
            echo "package-lock.json exists"
            cat package-lock.json
          else
            echo "package-lock.json does not exist"
          fi
      - name: Clear npm cache
        run: npm cache clean --force
      - name: Install dependencies
        run: npm install
      - name: Run tests with coverage
        run: npm run test:cov
      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coverage
  deploy:
    needs: test
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy codematic-youtube-backend API
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script_stop: true
          command_timeout: 200m
          script: |
            # Install Docker Compose if not present
            if ! command -v docker-compose &> /dev/null; then
              sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            fi
            cd /home/projects/codematics/codematic-youtube-backend
            git pull
            docker-compose down
            docker system prune -af
            docker-compose build --force-rm --no-cache --compress
            docker-compose up -d
            if docker-compose ps | grep -q "codematic-youtube-backend-container"; then
              echo "Deployment successful"
            else
              echo "Deployment failed"
              exit 1
            fi